export enum BatchEventType {
  BATCH_STARTED = 'BATCH_STARTED',
  BATCH_WEIGHING = 'BATCH_WEIGHING',
  BATCH_MIXING = 'BATCH_MIXING',
  BATCH_COMPLETE = 'BATCH_COMPLETE',
  BATCH_LOADED = 'BATCH_LOADED',
  BATCH_REJECTED = 'BATCH_REJECTED',
}
