services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: otl
      POSTGRES_PASSWORD: otl_dev
      POSTGRES_DB: otl_core
    volumes:
      - otl_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U otl -d otl_core']
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  otl_pgdata:
