export enum OrderStatus {
  DRAFT = 'DRAFT',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum TicketStatus {
  CREATED = 'CREATED',
  DISPATCHED = 'DISPATCHED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  VOIDED = 'VOIDED',
}

export enum LoadStatus {
  SCHEDULED = 'SCHEDULED',
  LOADING = 'LOADING',
  LOADED = 'LOADED',
  EN_ROUTE = 'EN_ROUTE',
  ON_SITE = 'ON_SITE',
  POURING = 'POURING',
  RETURNING = 'RETURNING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  REJECTED = 'REJECTED',
}

export enum DeliveryState {
  PLANT_DEPARTED = 'PLANT_DEPARTED',
  GEOFENCE_ENTERED = 'GEOFENCE_ENTERED',
  ON_SITE_ARRIVED = 'ON_SITE_ARRIVED',
  POUR_STARTED = 'POUR_STARTED',
  POUR_COMPLETED = 'POUR_COMPLETED',
  SITE_DEPARTED = 'SITE_DEPARTED',
  PLANT_RETURNED = 'PLANT_RETURNED',
  WASHOUT_COMPLETED = 'WASHOUT_COMPLETED',
}

export enum UnitOfMeasure {
  CUBIC_YARDS = 'CY',
  CUBIC_METERS = 'CM',
}
